apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: bitnami/mongodb:latest
        name: mongodb
        ports:
        - containerPort: 27017
      restartPolicy: Always   