apiVersion: v1
kind: Service
metadata:
  name: service-mongodb
  namespace: backend
spec:
    ports:
        - protocol: TCP
          port: 27017
          targetPort: 27017
    selector:
        app: mongodb
    type: LoadBalancer