apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-node
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - image: bebord95/backend-so2:1.1
        name: apinode
        ports:
        - containerPort: 80
      restartPolicy: Always