apiVersion: v1
kind: Service
metadata:
  name: service-api-node
  namespace: backend
spec:
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
    selector:
        app: node
    type: LoadBalancer  