apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-web
  namespace: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate 
  template:
    metadata:
      labels:
        app: app-web
    spec:
      containers:
      - image: bebord95/frontend-so2:1.1
        name: app-web
        ports:
        - containerPort: 80
      restartPolicy: Always